version: "3.11"

services:

  fastapi:
    build: .
    container_name: laza_project
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000 --proxy-headers
    volumes:
      - .:/app
      - media_volume:/uploads
    env_file:
      - ../LazaProject/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    container_name: laza_project_database
    image: postgres:15.0-alpine
    env_file:
      - ../LazaFastApiProject/.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    entrypoint: /bin/sh -c "if [ \"\$DATABASE\" = \"postgres\" ]; then echo 'Waiting for postgres...'; while ! nc -z \$SQL_HOST \$SQL_PORT; do sleep 0.1; done; echo 'PostgreSQL started'; fi; \$@"


volumes:
  media_volume:

